In [2]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

# Regression

## Task 1
You have the observation results of time that a person spent in a line in relation to the number of people in the line.

Observation	Number of people in a line, 	Time spent in the store (min), 
Below, the table data is presented in a row format, in case the table is not copied (you can save it as a CSV file using any text editor, or paste it into Azure ML Studio using Enter Data Manually item.

```
id,X,Y
1,5,12
2,17,45
3,9,18
4,13,25
5,12,23
6,7,18
7,18,43
8,20,36
9,22,66
10,24,78
```
Train the linear regression model to predict the values and enter the specified parameters.

Find the sample mean $\overline X$:

In [5]:
X = np.array([5, 17, 9, 13, 12, 7, 18, 20, 22, 24])
print(f"Sample mean X = {np.average(X)}")

Sample mean X = 14.7


Find the sample mean $\overline Y$:

In [6]:
y = np.array([12, 45, 18, 25, 23, 18, 43, 36, 66, 78])
print(f"Sample mean y = {np.average(y)}")

Sample mean y = 36.4


In [7]:
# Train the linear regression model to predict the values and enter the specified parameters.
model = LinearRegression()
model.fit(X.reshape(-1, 1), y)

LinearRegression()

Calculate the coefficient $\theta_1$

In [13]:
print(*model.coef_) # Поинтеры в питоне ахахха

3.107603262299395


Calculate the coefficient $\theta_0$

In [14]:
print(model.intercept_)

-9.281767955801108


Estimate the model accuracy by calculating R-squared statistics, $R^2$:

In [15]:
r_sq = model.score(X.reshape(-1, 1), y)
print(f"Точность модели {r_sq}")

Точность модели 0.8523827265066054


### Ref:
[Линейная регрессия на Python: объясняем на пальцах](https://proglib.io/p/linear-regression)

## Task 2
[The provided dataset](https://courses.openedu.ru/assets/courseware/v1/a11f0b9cb0074fdacc112eee71eb0b67/asset-v1:ITMOUniversity+INTROMLAAISBENG+spring_2023_ITMO_mag+type@asset+block/candy-data.csv) consists of the Halloween candy ranking (of the best, or at least the most popular, sweets in America). Train the multivariate linear regression model. The predictors are as follows: **chocolate, fruity, caramel, peanutyalmondy, nougat, crispedricewafer, hard, bar, pluribus, sugarpercent, pricepercent**, the response is **winpercent**.

As a training set, use the data from the file. Do not include the following candies: **Caramel Apple Pops, Nestle Crunch**. Train the model. In Azure ML Studio, specify the random seed = 2019 in the parameters of Linear Regression item.


In [16]:
df_url = "https://courses.openedu.ru/assets/courseware/v1/a11f0b9cb0074fdacc112eee71eb0b67/asset-v1:ITMOUniversity+INTROMLAAISBENG+spring_2023_ITMO_mag+type@asset+block/candy-data.csv"
df = pd.read_csv(df_url)
df.head()

competitorname 
 chocolate 
 fruity 
 caramel 
 peanutyalmondy 
 nougat 
 crispedricewafer 
 hard 
 bar 
 pluribus 
 sugarpercent 
 pricepercent 
 winpercent 
 Y 
 
 
 
 
 0 
 100 Grand 
 1 
 0 
 1 
 0 
 0 
 1 
 0 
 1 
 0 
 0.732 
 0.860 
 66.971725 
 1 
 
 
 1 
 3 Musketeers 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0.604 
 0.511 
 67.602936 
 1 
 
 
 2 
 One dime 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0.011 
 0.116 
 32.261086 
 0 
 
 
 3 
 One quarter 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0.011 
 0.511 
 46.116505 
 0 
 
 
 4 
 Air Heads 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0.906 
 0.511 
 52.341465 
 1

In [20]:
df.columns

Index(['competitorname', 'chocolate', 'fruity', 'caramel', 'peanutyalmondy',
       'nougat', 'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent',
       'pricepercent', 'winpercent', 'Y'],
      dtype='object')

In [24]:
task_df = df.loc[
    (df.competitorname != "Caramel Apple Pops") &
    (df.competitorname != "Nestle Crunch")
]

In [30]:
X_train = task_df.drop(columns=["competitorname","winpercent", "Y"])
y_train = task_df["winpercent"]

In [31]:
X_train

chocolate 
 fruity 
 caramel 
 peanutyalmondy 
 nougat 
 crispedricewafer 
 hard 
 bar 
 pluribus 
 sugarpercent 
 pricepercent 
 
 
 
 
 0 
 1 
 0 
 1 
 0 
 0 
 1 
 0 
 1 
 0 
 0.732 
 0.860 
 
 
 1 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0.604 
 0.511 
 
 
 2 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0.011 
 0.116 
 
 
 3 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0.011 
 0.511 
 
 
 4 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0.906 
 0.511 
 
 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 
 
 65 
 1 
 0 
 1 
 1 
 0 
 1 
 0 
 1 
 0 
 0.604 
 0.651 
 
 
 66 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0.069 
 0.116 
 
 
 67 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0.069 
 0.116 
 
 
 68 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0.151 
 0.220 
 
 
 69 
 0 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 0.569 
 0.058 
 
 
 
 68 rows × 11 columns

In [32]:
candy_model = LinearRegression()
candy_model.fit(X_train, y_train)

LinearRegression()

In [36]:
task_test_df = df.loc[
    (df.competitorname == "Caramel Apple Pops") |
    (df.competitorname == "Nestle Crunch")
]

task_test_df

competitorname 
 chocolate 
 fruity 
 caramel 
 peanutyalmondy 
 nougat 
 crispedricewafer 
 hard 
 bar 
 pluribus 
 sugarpercent 
 pricepercent 
 winpercent 
 Y 
 
 
 
 
 9 
 Caramel Apple Pops 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0.604 
 0.325 
 34.517681 
 0 
 
 
 43 
 Nestle Crunch 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0.313 
 0.767 
 66.470680 
 1

In [37]:
X_test = task_test_df.drop(columns=["competitorname","winpercent", "Y"])
y_test = task_test_df["winpercent"]

### Enter the predicted value of winpercent for Caramel Apple Pops:
### Enter the predicted value of winpercent for Nestle Crunch:

In [39]:
candy_model.predict(X_test)

array([54.29127151, 61.06849114])

### Enter the predicted value of winpercent for a candy with the following parameters:
$[0, 1, 1, 0, 0, 1, 0, 0, 0, 0.162, 0.71]$

In [78]:
columns = ['chocolate', 'fruity', 'caramel', 'peanutyalmondy',
       'nougat', 'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent',
       'pricepercent'
]
random_candy = np.array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0.162, 0.71]).reshape(1, 11)
random_candy

array([[0. , 1. , 1. , 0. , 0. , 1. , 0. , 0. , 0. ,
 0.162, 0.71 ]])

In [79]:
X_test_2 = pd.DataFrame(random_candy, columns=columns)
X_test_2

chocolate 
 fruity 
 caramel 
 peanutyalmondy 
 nougat 
 crispedricewafer 
 hard 
 bar 
 pluribus 
 sugarpercent 
 pricepercent 
 
 
 
 
 0 
 0.0 
 1.0 
 1.0 
 0.0 
 0.0 
 1.0 
 0.0 
 0.0 
 0.0 
 0.162 
 0.71

In [80]:
candy_model.predict(X_test_2)

array([53.87339852])